android.useAndroidX=true

org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

GROUP=com.commit451.adapterlayout
VERSION_NAME=1.2.1

POM_NAME=AdapterLayout
POM_DESCRIPTION=ViewGroup backed by RecyclerView.Adapter, without recycling
POM_INCEPTION_YEAR=2018
POM_URL=https://github.com/Commit451/AdapterLayout/

POM_LICENSE_NAME=The Apache Software License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=repo

POM_SCM_URL=https://github.com/Commit451/AdapterLayout/
POM_SCM_CONNECTION=scm:git:git://github.com/Commit451/AdapterLayout.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/Commit451/AdapterLayout.git

POM_DEVELOPER_ID=Commit451
POM_DEVELOPER_NAME=Commit 451
POM_DEVELOPER_URL=https://github.com/Commit451/

SONATYPE_CONNECT_TIMEOUT_SECONDS=60
SONATYPE_CLOSE_TIMEOUT_SECONDS=900
